### ISSUE TITLE
Optimise CSS classes for icons

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1680]
Here's our typical icon class definition (in this case `icon-spinner`). This results in contents of `.icon-mixin` to be repeated for **every** **single** icon class we have, even though the only difference is `content` property. Instead, every icon should have **two** classes assigned to it: general `icon` class (with common properties) and the one specific for this icon, which will have only `content` and possibly `font-size`.

```css
.icon-mixin(@fontface) {
  font-weight: normal;
  font-style: normal;
  font-variant: normal;
  text-transform: none;
  speak: none;
  line-height: 1;
  color: @admin-dark-gray;

  &:before,
  &:after {
    font-family: @fontface, monospace !important;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
}

.icon() {
  .icon-mixin('icomoon');
}

.icon-spinner {
  .icon();
  &:before {
    content: "\e007";
  }
}
```
