### ISSUE TITLE
Help text and max length counter overlap

### ISSUE THREAD

**Issue by reisfmb** [enonic/lib-admin-ui#2598]
Need to fix for textline and textarea:

![image](https://user-images.githubusercontent.com/67838246/171031591-57133eed-a743-46d5-b659-7c6fcedce45b.png)

**Comment by reisfmb** [comment]
@alansemenov 

Quick fix would be:
```css
&.max-length-limited {
    + .help-text {
        padding-right: 175px;
    }
}
```
I've used `175px` because it seems to be enough right padding for English text. The problem with this approach is that `175px` might not be the best depending on the language... For example, is too much for `160 tegn igjen`:

![image](https://user-images.githubusercontent.com/67838246/171057014-cec94afb-1590-438d-834f-9a4e70647cb1.png)

How should we proceed?
